bundler_args:
  --without development debug darwin

language: ruby

before_script:
  - "sudo killall redis-server"
  - "spec/redis-server &"
  - "sleep 5"

script: "bundle exec rspec --backtrace"

rvm:
  - 1.9.2
  - 1.9.3